import React, { useState, useRef, useEffect, useCallback } from 'react';
import { Mountain, X, Download, MapPin, ChevronDown } from 'lucide-react';

import { SelectionMap } from './MapComponents';
import { getCenteredBounds, getTilesForBounds, getDistanceMeters, formatDistance, elevationSource, orthoSources, TERRAIN_STORAGE_KEY } from '../utils';

/**
 * Generate OBJ mesh from heightmap data
 */
const generateOBJMesh = (heightData, width, height, bounds, vScale) => {
  const [[lat1, lon1], [lat2, lon2]] = bounds;
  const realWidth = getDistanceMeters(lat1, lon1, lat1, lon2);
  const realHeight = getDistanceMeters(lat1, lon1, lat2, lon1);

  let obj = '# Terrain mesh generated by Negativ Tools\n';
  obj += '# Coordinate system: Z-up (Rhino/3ds Max compatible)\n';
  obj += `# Bounds: ${lat1},${lon1} to ${lat2},${lon2}\n`;
  obj += `# Real size: ${realWidth.toFixed(0)}m x ${realHeight.toFixed(0)}m\n`;
  obj += `# Vertical scale: ${vScale}x\n\n`;

  // Generate vertices (Z-up coordinate system: X=width, Y=depth, Z=height)
  obj += '# Vertices\n';
  const stepX = realWidth / (width - 1);
  const stepY = realHeight / (height - 1);

  for (let row = 0; row < height; row++) {
    for (let col = 0; col < width; col++) {
      const px = col * stepX;
      const py = row * stepY;
      const pz = heightData[row * width + col] * vScale;
      obj += `v ${px.toFixed(3)} ${py.toFixed(3)} ${pz.toFixed(3)}\n`;
    }
  }

  // Generate texture coordinates
  obj += '\n# Texture coordinates\n';
  for (let row = 0; row < height; row++) {
    for (let col = 0; col < width; col++) {
      const u = col / (width - 1);
      const v = 1 - (row / (height - 1));
      obj += `vt ${u.toFixed(4)} ${v.toFixed(4)}\n`;
    }
  }

  // Generate normals (Z-up: normal pointing in +Z direction)
  obj += '\n# Normals\n';
  for (let row = 0; row < height; row++) {
    for (let col = 0; col < width; col++) {
      // Calculate normal from surrounding vertices
      let nx = 0, ny = 0, nz = 1;
      if (col > 0 && col < width - 1 && row > 0 && row < height - 1) {
        const hL = heightData[row * width + (col - 1)] * vScale;
        const hR = heightData[row * width + (col + 1)] * vScale;
        const hU = heightData[(row - 1) * width + col] * vScale;
        const hD = heightData[(row + 1) * width + col] * vScale;
        // Gradient gives us the slope, normal is perpendicular
        nx = (hL - hR) / (2 * stepX);
        ny = (hU - hD) / (2 * stepY);
        const len = Math.sqrt(nx * nx + ny * ny + 1);
        nx /= len;
        ny /= len;
        nz = 1 / len;
      }
      obj += `vn ${nx.toFixed(4)} ${ny.toFixed(4)} ${nz.toFixed(4)}\n`;
    }
  }

  // Generate faces (triangles)
  obj += '\n# Faces\n';
  for (let row = 0; row < height - 1; row++) {
    for (let col = 0; col < width - 1; col++) {
      const i1 = row * width + col + 1;
      const i2 = row * width + col + 2;
      const i3 = (row + 1) * width + col + 1;
      const i4 = (row + 1) * width + col + 2;

      // Two triangles per quad (counter-clockwise winding for Z-up)
      obj += `f ${i1}/${i1}/${i1} ${i2}/${i2}/${i2} ${i3}/${i3}/${i3}\n`;
      obj += `f ${i2}/${i2}/${i2} ${i4}/${i4}/${i4} ${i3}/${i3}/${i3}\n`;
    }
  }

  return obj;
};

/**
 * TerrainModal - 3D Terrain Mesh Download component
 */
export const TerrainModal = ({ isOpen, onClose }) => {
  // Load saved settings
  const loadSettings = () => {
    try {
      const saved = localStorage.getItem(TERRAIN_STORAGE_KEY);
      if (saved) return JSON.parse(saved);
    } catch (e) {}
    return null;
  };

  const savedSettings = loadSettings();

  const [selectedSource, setSelectedSource] = useState(
    orthoSources.find(s => s.id === savedSettings?.sourceId) || orthoSources[0]
  );
  const [center, setCenter] = useState(savedSettings?.center || null);
  const [mapView, setMapView] = useState(savedSettings?.mapView || [50.0755, 14.4378]);
  const [mapZoom, setMapZoom] = useState(savedSettings?.mapZoom || 14);
  const [tileZoom, setTileZoom] = useState(savedSettings?.tileZoom || 12);
  const [gridSize, setGridSize] = useState(savedSettings?.gridSize || 3);
  const [downloading, setDownloading] = useState(false);
  const [downloadProgress, setDownloadProgress] = useState(0);
  const [searchQuery, setSearchQuery] = useState('');
  const [currentMapZoom, setCurrentMapZoom] = useState(14);
  const [searchResults, setSearchResults] = useState([]);
  const [searching, setSearching] = useState(false);
  const [verticalScale, setVerticalScale] = useState(savedSettings?.verticalScale || 1);
  const [meshResolution, setMeshResolution] = useState(savedSettings?.meshResolution || 256);
  const [exportFormat, setExportFormat] = useState(savedSettings?.exportFormat || 'obj');
  const [generateTexture, setGenerateTexture] = useState(savedSettings?.generateTexture ?? true);
  const [textureSource, setTextureSource] = useState(savedSettings?.textureSource || 'google');
  const [showDetails, setShowDetails] = useState(false);

  const modalRef = useRef(null);

  const handleZoomChange = useCallback((zoom) => {
    setCurrentMapZoom(Math.round(zoom));
  }, []);

  // Save settings
  useEffect(() => {
    const settings = {
      sourceId: selectedSource.id,
      center,
      mapView,
      mapZoom,
      tileZoom,
      gridSize,
      verticalScale,
      meshResolution,
      exportFormat,
      generateTexture,
      textureSource,
    };
    localStorage.setItem(TERRAIN_STORAGE_KEY, JSON.stringify(settings));
  }, [selectedSource, center, mapView, mapZoom, tileZoom, gridSize, verticalScale, meshResolution, exportFormat, generateTexture, textureSource]);

  // Grid and zoom options
  const gridSizes = [
    { value: 1, label: '1×1' },
    { value: 2, label: '2×2' },
    { value: 3, label: '3×3' },
    { value: 4, label: '4×4' },
  ];

  const terrainZooms = [
    { value: 10, label: '10 (~1km/tile)' },
    { value: 11, label: '11 (~500m/tile)' },
    { value: 12, label: '12 (~250m/tile)' },
    { value: 13, label: '13 (~125m/tile)' },
    { value: 14, label: '14 (~60m/tile)' },
  ];

  const meshResolutions = [
    { value: 128, label: '128×128' },
    { value: 256, label: '256×256' },
    { value: 512, label: '512×512' },
  ];

  const handleMapClick = useCallback((latlng) => {
    setCenter(latlng);
  }, []);

  // Search
  const handleSearch = async () => {
    if (!searchQuery.trim()) return;

    const coordMatch = searchQuery.match(/^(-?\d+\.?\d*)\s*,\s*(-?\d+\.?\d*)$/);
    if (coordMatch) {
      const lat = parseFloat(coordMatch[1]);
      const lon = parseFloat(coordMatch[2]);
      if (lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180) {
        setCenter([lat, lon]);
        setMapView([lat, lon]);
        setMapZoom(14);
        setSearchResults([]);
        return;
      }
    }

    setSearching(true);
    try {
      const response = await fetch(
        `https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(searchQuery)}&limit=5&addressdetails=1`
      );
      const data = await response.json();
      setSearchResults(data.map(item => ({
        name: item.display_name,
        lat: parseFloat(item.lat),
        lon: parseFloat(item.lon),
      })));
    } catch (e) {
      console.error('Search failed:', e);
    }
    setSearching(false);
  };

  const selectSearchResult = (result) => {
    setCenter([result.lat, result.lon]);
    setMapView([result.lat, result.lon]);
    setMapZoom(14);
    setSearchResults([]);
    setSearchQuery('');
  };

  // Download terrain and generate mesh
  const handleDownload = async () => {
    if (!center) return;

    setDownloading(true);
    setDownloadProgress(0);

    try {
      // Bounds centered exactly on clicked point
      const dlBounds = getCenteredBounds(center, tileZoom, gridSize);
      const { tiles, cols, rows, originTile } = getTilesForBounds(dlBounds, tileZoom);

      // Create canvas for all tiles that intersect the bounds
      const tileSize = 256;
      const totalTiles = tiles.length;
      const canvas = document.createElement('canvas');
      canvas.width = cols * tileSize;
      canvas.height = rows * tileSize;
      const ctx = canvas.getContext('2d', { willReadFrequently: true });

      // Load elevation tiles
      let loaded = 0;
      for (const tile of tiles) {
        await new Promise((resolve) => {
          const img = new Image();
          img.crossOrigin = 'anonymous';
          img.onload = () => {
            ctx.drawImage(img, tile.gx * tileSize, tile.gy * tileSize, tileSize, tileSize);
            resolve(true);
          };
          img.onerror = () => {
            ctx.fillStyle = '#808080';
            ctx.fillRect(tile.gx * tileSize, tile.gy * tileSize, tileSize, tileSize);
            resolve(false);
          };
          img.src = elevationSource.tileUrl(tileZoom, tile.x, tile.y);
        });
        loaded++;
        setDownloadProgress((loaded / totalTiles) * 50);
      }

      // Calculate pixel crop region within the full tile canvas
      // Convert bounds corners to fractional tile coordinates, then to pixels
      const n = Math.pow(2, tileZoom);
      const nwPixelX = ((dlBounds[0][1] + 180) / 360 * n - originTile.x) * tileSize;
      const nwPixelY = ((1 - Math.log(Math.tan(dlBounds[0][0] * Math.PI / 180) + 1 / Math.cos(dlBounds[0][0] * Math.PI / 180)) / Math.PI) / 2 * n - originTile.y) * tileSize;
      const sePixelX = ((dlBounds[1][1] + 180) / 360 * n - originTile.x) * tileSize;
      const sePixelY = ((1 - Math.log(Math.tan(dlBounds[1][0] * Math.PI / 180) + 1 / Math.cos(dlBounds[1][0] * Math.PI / 180)) / Math.PI) / 2 * n - originTile.y) * tileSize;

      const cropX = Math.round(nwPixelX);
      const cropY = Math.round(nwPixelY);
      const cropW = Math.round(sePixelX - nwPixelX);
      const cropH = Math.round(sePixelY - nwPixelY);

      // Resample cropped region to desired mesh resolution
      const outputSize = meshResolution;
      const imageData = ctx.getImageData(cropX, cropY, cropW, cropH);
      const heightData = new Float32Array(outputSize * outputSize);

      const scaleX = cropW / outputSize;
      const scaleY = cropH / outputSize;

      let minHeight = Infinity;
      let maxHeight = -Infinity;

      for (let y = 0; y < outputSize; y++) {
        for (let x = 0; x < outputSize; x++) {
          const srcX = Math.floor(x * scaleX);
          const srcY = Math.floor(y * scaleY);
          const idx = (srcY * cropW + srcX) * 4;

          const r = imageData.data[idx];
          const g = imageData.data[idx + 1];
          const b = imageData.data[idx + 2];

          const height = elevationSource.decodeHeight(r, g, b);
          heightData[y * outputSize + x] = height;

          minHeight = Math.min(minHeight, height);
          maxHeight = Math.max(maxHeight, height);
        }
        setDownloadProgress(50 + (y / outputSize) * 30);
      }

      // Normalize heights (optional - subtract min to start from 0)
      for (let i = 0; i < heightData.length; i++) {
        heightData[i] -= minHeight;
      }

      setDownloadProgress(85);

      // Generate filename
      const date = new Date();
      const dateStr = date.toISOString().slice(0, 10).replace(/-/g, '');
      const latStr = center[0].toFixed(3).replace('.', '_');
      const lonStr = center[1].toFixed(3).replace('.', '_');
      const baseFilename = `terrain_${latStr}_${lonStr}_z${tileZoom}_${dateStr}`;

      // Generate and download OBJ
      const objContent = generateOBJMesh(heightData, outputSize, outputSize, dlBounds, verticalScale);
      const objBlob = new Blob([objContent], { type: 'text/plain' });
      const objUrl = URL.createObjectURL(objBlob);
      const objLink = document.createElement('a');
      objLink.download = `${baseFilename}.obj`;
      objLink.href = objUrl;
      objLink.click();
      URL.revokeObjectURL(objUrl);

      setDownloadProgress(90);

      // Generate texture if requested
      if (generateTexture) {
        const textureTileZoom = Math.min(tileZoom + 2, 19);
        const { tiles: texTileList, cols: texCols, rows: texRows, originTile: texOrigin } = getTilesForBounds(dlBounds, textureTileZoom);

        const texTileSize = 256;
        const texFullCanvas = document.createElement('canvas');
        texFullCanvas.width = texCols * texTileSize;
        texFullCanvas.height = texRows * texTileSize;
        const texFullCtx = texFullCanvas.getContext('2d');

        const textureUrl = textureSource === 'google'
          ? (z, x, y) => `https://mt1.google.com/vt/lyrs=s&x=${x}&y=${y}&z=${z}`
          : (z, x, y) => `https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${z}/${y}/${x}`;

        for (const tile of texTileList) {
          await new Promise((resolve) => {
            const img = new Image();
            img.crossOrigin = 'anonymous';
            img.onload = () => {
              texFullCtx.drawImage(img, tile.gx * texTileSize, tile.gy * texTileSize, texTileSize, texTileSize);
              resolve(true);
            };
            img.onerror = () => resolve(false);
            img.src = textureUrl(textureTileZoom, tile.x, tile.y);
          });
        }

        // Crop texture to exact bounds
        const texN = Math.pow(2, textureTileZoom);
        const texCropX = Math.round(((dlBounds[0][1] + 180) / 360 * texN - texOrigin.x) * texTileSize);
        const texCropY = Math.round(((1 - Math.log(Math.tan(dlBounds[0][0] * Math.PI / 180) + 1 / Math.cos(dlBounds[0][0] * Math.PI / 180)) / Math.PI) / 2 * texN - texOrigin.y) * texTileSize);
        const texCropX2 = Math.round(((dlBounds[1][1] + 180) / 360 * texN - texOrigin.x) * texTileSize);
        const texCropY2 = Math.round(((1 - Math.log(Math.tan(dlBounds[1][0] * Math.PI / 180) + 1 / Math.cos(dlBounds[1][0] * Math.PI / 180)) / Math.PI) / 2 * texN - texOrigin.y) * texTileSize);

        const textureSize = meshResolution * 2;
        const textureCanvas = document.createElement('canvas');
        textureCanvas.width = textureSize;
        textureCanvas.height = textureSize;
        const textureCtx = textureCanvas.getContext('2d');
        textureCtx.drawImage(texFullCanvas, texCropX, texCropY, texCropX2 - texCropX, texCropY2 - texCropY, 0, 0, textureSize, textureSize);

        textureCanvas.toBlob((blob) => {
          const texUrl = URL.createObjectURL(blob);
          const texLink = document.createElement('a');
          texLink.download = `${baseFilename}_texture.jpg`;
          texLink.href = texUrl;
          setTimeout(() => {
            texLink.click();
            URL.revokeObjectURL(texUrl);
          }, 200);
        }, 'image/jpeg', 0.9);
      }

      setDownloadProgress(100);

      setTimeout(() => {
        setDownloading(false);
        setDownloadProgress(0);
      }, 500);

    } catch (error) {
      console.error('Download failed:', error);
      setDownloading(false);
      setDownloadProgress(0);
    }
  };

  // Calculate bounds centered exactly on clicked point
  const bounds = getCenteredBounds(center, tileZoom, gridSize);

  // Keyboard shortcuts
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (e) => {
      // Don't trigger if typing in input
      if (e.target.tagName === 'INPUT') return;

      switch (e.key) {
        case '+':
        case '=':
          setTileZoom(z => Math.min(14, z + 1));
          break;
        case '-':
          setTileZoom(z => Math.max(10, z - 1));
          break;
        case 'Enter':
          if (center && !downloading) {
            handleDownload();
          }
          break;
        case 'Escape':
          onClose();
          break;
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, center, downloading, onClose]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div
        ref={modalRef}
        className="bg-neutral-900 rounded-lg w-full h-full shadow-2xl overflow-hidden flex flex-col"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="px-5 py-4 border-b border-neutral-700 flex items-center justify-between flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-white rounded-lg flex items-center justify-center">
              <Mountain className="w-5 h-5 text-neutral-900" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-white">3D Terrain</h2>
              <p className="text-sm text-neutral-400">SRTM Elevation Data → OBJ Mesh • <span className="text-neutral-500">ESC zavřít, +/- zoom, Enter stáhnout</span></p>
            </div>
          </div>
          <button onClick={onClose} className="text-neutral-400 hover:text-white p-2 hover:bg-neutral-800 rounded-lg transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 flex overflow-hidden">
          {/* Map */}
          <SelectionMap
            mapView={mapView}
            mapZoom={mapZoom}
            tileUrl={selectedSource.url}
            bounds={bounds}
            center={center}
            onMapClick={handleMapClick}
            onZoomChange={handleZoomChange}
          >
            <div className="absolute bottom-4 left-4 z-[1000] bg-black/70 text-white text-xs px-2 py-1 rounded">
              Zoom: {currentMapZoom}
            </div>
          </SelectionMap>

          {/* Sidebar */}
          <div className="w-96 bg-neutral-800 border-l border-neutral-700 flex flex-col overflow-y-auto">
            <div className="p-5 space-y-6">
              {/* Search */}
              <div>
                <label className="text-sm font-medium text-neutral-300 mb-2 block">
                  Hledat místo
                </label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={e => setSearchQuery(e.target.value)}
                    onKeyDown={e => e.key === 'Enter' && handleSearch()}
                    placeholder="Adresa nebo 50.0755, 14.4378"
                    className="flex-1 px-3 py-2.5 text-sm bg-neutral-700 border border-neutral-600 rounded-lg text-white placeholder-neutral-500 focus:outline-none focus:border-white focus:ring-1 focus:ring-white"
                  />
                  <button
                    onClick={handleSearch}
                    disabled={searching}
                    className="px-3 py-2.5 bg-white text-neutral-900 rounded-lg hover:bg-neutral-200 disabled:bg-neutral-600 transition-colors"
                  >
                    {searching ? '...' : <MapPin className="w-4 h-4" />}
                  </button>
                </div>
                {searchResults.length > 0 && (
                  <div className="mt-2 bg-neutral-700 border border-neutral-600 rounded-lg max-h-48 overflow-y-auto">
                    {searchResults.map((result, i) => (
                      <button key={i} onClick={() => selectSearchResult(result)}
                        className="w-full px-3 py-2 text-left text-sm hover:bg-neutral-600 border-b border-neutral-600 last:border-0">
                        <div className="truncate text-white">{result.name}</div>
                        <div className="text-xs font-mono text-neutral-400">
                          {result.lat.toFixed(5)}, {result.lon.toFixed(5)}
                        </div>
                      </button>
                    ))}
                  </div>
                )}
              </div>

              {/* Map Source */}
              <div>
                <label className="text-sm font-medium text-neutral-300 mb-2 block">Zdroj mapy</label>
                <div className="flex gap-2">
                  {orthoSources.map(source => (
                    <button
                      key={source.id}
                      onClick={() => setSelectedSource(source)}
                      className={`flex-1 py-2.5 rounded-lg text-sm font-medium transition-all ${
                        selectedSource.id === source.id
                          ? 'bg-white text-neutral-900'
                          : 'bg-neutral-700 text-neutral-300 hover:bg-neutral-600'
                      }`}
                    >
                      {source.name}
                    </button>
                  ))}
                </div>
              </div>

              {/* Source info */}
              <div>
                <label className="text-sm font-medium text-neutral-300 mb-2 block">Zdroj výškových dat</label>
                <div className="bg-neutral-700/50 rounded-lg p-3">
                  <div className="text-sm text-white font-medium">{elevationSource.name}</div>
                  <div className="text-xs text-neutral-400 mt-1">{elevationSource.attribution}</div>
                  <div className="text-[10px] text-neutral-500 mt-2">
                    * Bezplatný zdroj bez API klíče
                  </div>
                </div>
              </div>

              {/* Tile zoom - Slider */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-sm font-medium text-neutral-300">
                    Detail terénu (zoom)
                  </label>
                  <span className="text-sm font-mono text-white">{tileZoom}</span>
                </div>
                <input
                  type="range"
                  min={10}
                  max={14}
                  value={tileZoom}
                  onChange={e => setTileZoom(parseInt(e.target.value))}
                  className="w-full h-2 bg-neutral-700 rounded-lg appearance-none cursor-pointer accent-white"
                />
                <div className="flex justify-between text-xs text-neutral-500 mt-1">
                  <span>10</span>
                  <span>11</span>
                  <span>12</span>
                  <span>13</span>
                  <span>14</span>
                </div>
                <button
                  onClick={() => setTileZoom(Math.min(14, Math.max(10, currentMapZoom)))}
                  className="text-xs text-white hover:text-neutral-300 mt-2"
                >
                  Použít aktuální zoom mapy ({currentMapZoom})
                </button>
              </div>

              {/* Grid size */}
              <div>
                <label className="text-sm font-medium text-neutral-300 mb-2 block">Velikost oblasti</label>
                <div className="grid grid-cols-4 gap-2">
                  {gridSizes.map(g => (
                    <button
                      key={g.value}
                      onClick={() => setGridSize(g.value)}
                      className={`py-2.5 text-sm font-medium rounded-lg transition-all ${
                        gridSize === g.value
                          ? 'bg-white text-neutral-900'
                          : 'bg-neutral-700 text-neutral-300 hover:bg-neutral-600'
                      }`}
                    >
                      {g.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Mesh resolution */}
              <div>
                <label className="text-sm font-medium text-neutral-300 mb-2 block">Rozlišení mesh</label>
                <div className="grid grid-cols-3 gap-2">
                  {meshResolutions.map(r => (
                    <button
                      key={r.value}
                      onClick={() => setMeshResolution(r.value)}
                      className={`py-2.5 text-sm font-medium rounded-lg transition-all ${
                        meshResolution === r.value
                          ? 'bg-white text-neutral-900'
                          : 'bg-neutral-700 text-neutral-300 hover:bg-neutral-600'
                      }`}
                    >
                      {r.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Vertical scale */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-sm font-medium text-neutral-300">
                    Vertikální měřítko
                  </label>
                  <span className="text-sm font-mono text-white">{verticalScale}×</span>
                </div>
                <input
                  type="range"
                  min="0.5"
                  max="5"
                  step="0.5"
                  value={verticalScale}
                  onChange={(e) => setVerticalScale(parseFloat(e.target.value))}
                  className="w-full h-2 bg-neutral-700 rounded-lg appearance-none cursor-pointer accent-white"
                />
                <div className="flex justify-between text-xs text-neutral-500 mt-1">
                  <span>0.5×</span>
                  <span>1× (reálné)</span>
                  <span>5×</span>
                </div>
              </div>

              {/* Texture option */}
              <div>
                <label className="flex items-center gap-2 cursor-pointer mb-3">
                  <input
                    type="checkbox"
                    checked={generateTexture}
                    onChange={(e) => setGenerateTexture(e.target.checked)}
                    className="w-4 h-4 rounded border-neutral-600 bg-neutral-700 text-white focus:ring-white"
                  />
                  <span className="text-sm font-medium text-neutral-300">
                    Stáhnout ortho texturu
                  </span>
                </label>
                {generateTexture && (
                  <div className="flex gap-2 pl-6">
                    <button
                      onClick={() => setTextureSource('google')}
                      className={`flex-1 py-2.5 text-sm font-medium rounded-lg transition-all ${
                        textureSource === 'google'
                          ? 'bg-white text-neutral-900'
                          : 'bg-neutral-700 text-neutral-300 hover:bg-neutral-600'
                      }`}
                    >
                      Google
                    </button>
                    <button
                      onClick={() => setTextureSource('esri')}
                      className={`flex-1 py-2.5 text-sm font-medium rounded-lg transition-all ${
                        textureSource === 'esri'
                          ? 'bg-white text-neutral-900'
                          : 'bg-neutral-700 text-neutral-300 hover:bg-neutral-600'
                      }`}
                    >
                      Esri
                    </button>
                  </div>
                )}
              </div>

              {/* Details - Collapsible */}
              <div>
                <button
                  onClick={() => setShowDetails(!showDetails)}
                  className="w-full flex items-center justify-between text-sm font-medium text-neutral-300 hover:text-white transition-colors"
                >
                  <span>Detaily mesh</span>
                  <ChevronDown className={`w-4 h-4 transition-transform ${showDetails ? 'rotate-180' : ''}`} />
                </button>
                {showDetails && (
                  <div className="mt-3 bg-neutral-700/50 rounded-lg p-4 space-y-2">
                    <div className="flex justify-between text-sm">
                      <span className="text-neutral-400">Rozlišení:</span>
                      <span className="font-mono text-white">{meshResolution} × {meshResolution}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-neutral-400">Grid:</span>
                      <span className="font-mono text-white">{gridSize} × {gridSize} tiles</span>
                    </div>
                    {bounds && (
                      <div className="flex justify-between text-sm">
                        <span className="text-neutral-400">Oblast:</span>
                        <span className="font-mono text-white">
                          {formatDistance(getDistanceMeters(bounds[0][0], bounds[0][1], bounds[0][0], bounds[1][1]))} × {formatDistance(getDistanceMeters(bounds[0][0], bounds[0][1], bounds[1][0], bounds[0][1]))}
                        </span>
                      </div>
                    )}
                    <div className="flex justify-between text-sm">
                      <span className="text-neutral-400">Vertikální měřítko:</span>
                      <span className="font-mono text-white">{verticalScale}×</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-neutral-400">Formát:</span>
                      <span className="font-mono text-white">
                        OBJ {generateTexture ? '+ JPG texture' : ''}
                      </span>
                    </div>
                  </div>
                )}
              </div>

              {/* Download button */}
              <div className="pt-4 border-t border-neutral-700">
                {downloading ? (
                  <div className="space-y-3">
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-neutral-300 flex items-center gap-2">
                        <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                        Generuji mesh...
                      </span>
                      <span className="font-mono text-white">{Math.round(downloadProgress)}%</span>
                    </div>
                    <div className="w-full bg-neutral-700 rounded-full h-2">
                      <div className="bg-white h-2 rounded-full transition-all"
                           style={{ width: `${downloadProgress}%` }} />
                    </div>
                  </div>
                ) : (
                  <button
                    onClick={handleDownload}
                    disabled={!center}
                    className="w-full py-3.5 bg-white text-neutral-900 text-sm font-semibold rounded-lg hover:bg-neutral-200 disabled:bg-neutral-700 disabled:text-neutral-500 flex items-center justify-center gap-2 transition-colors"
                  >
                    <Download className="w-5 h-5" />
                    Stáhnout OBJ Mesh
                  </button>
                )}
                {!center && (
                  <p className="text-sm text-neutral-500 text-center mt-3">
                    Klikni na mapu pro výběr oblasti
                  </p>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
