import { getDistanceMeters } from './geoUtils';

/**
 * Generate OBJ terrain mesh from height data.
 * Coordinate system: Z-up (Rhino/3ds Max compatible)
 *
 * @param {Object} terrain - TerrainData from terrainLoader
 * @param {number} verticalScale - height multiplier
 * @returns {string} OBJ file content
 */
export const exportTerrainOBJ = (terrain, verticalScale = 1) => {
  const { heightData, resolution, bounds, realWidth, realHeight } = terrain;
  const width = resolution;
  const height = resolution;
  const [[lat1, lon1], [lat2, lon2]] = bounds;

  let obj = '# Terrain mesh generated by Negativ Tools\n';
  obj += '# Coordinate system: Z-up (Rhino/3ds Max compatible)\n';
  obj += `# Bounds: ${lat1},${lon1} to ${lat2},${lon2}\n`;
  obj += `# Real size: ${realWidth.toFixed(0)}m x ${realHeight.toFixed(0)}m\n`;
  obj += `# Vertical scale: ${verticalScale}x\n\n`;
  obj += 'o terrain\n';

  const stepX = realWidth / (width - 1);
  const stepY = realHeight / (height - 1);

  // Vertices
  for (let row = 0; row < height; row++) {
    for (let col = 0; col < width; col++) {
      const px = col * stepX;
      // heightData row 0 = NORTH. Target frame: +Y = NORTH, min-corner at
      // origin → north row maps to py = realHeight, south row to py = 0.
      const py = realHeight - row * stepY;
      const pz = heightData[row * width + col] * verticalScale;
      obj += `v ${px.toFixed(3)} ${py.toFixed(3)} ${pz.toFixed(3)}\n`;
    }
  }

  // Texture coordinates
  obj += '\n# Texture coordinates\n';
  for (let row = 0; row < height; row++) {
    for (let col = 0; col < width; col++) {
      const u = col / (width - 1);
      const v = 1 - (row / (height - 1));
      obj += `vt ${u.toFixed(4)} ${v.toFixed(4)}\n`;
    }
  }

  // Normals
  obj += '\n# Normals\n';
  for (let row = 0; row < height; row++) {
    for (let col = 0; col < width; col++) {
      let nx = 0, ny = 0, nz = 1;
      if (col > 0 && col < width - 1 && row > 0 && row < height - 1) {
        const hL = heightData[row * width + (col - 1)] * verticalScale;
        const hR = heightData[row * width + (col + 1)] * verticalScale;
        const hU = heightData[(row - 1) * width + col] * verticalScale;
        const hD = heightData[(row + 1) * width + col] * verticalScale;
        nx = (hL - hR) / (2 * stepX);
        // py now decreases with row (north = +Y). hU is the northern (larger
        // py) sample, hD the southern: n_y = -dh/dpy = (hD - hU)/(2·stepY).
        ny = (hD - hU) / (2 * stepY);
        const len = Math.sqrt(nx * nx + ny * ny + 1);
        nx /= len; ny /= len; nz = 1 / len;
      }
      obj += `vn ${nx.toFixed(4)} ${ny.toFixed(4)} ${nz.toFixed(4)}\n`;
    }
  }

  // Faces
  obj += '\n# Faces\n';
  for (let row = 0; row < height - 1; row++) {
    for (let col = 0; col < width - 1; col++) {
      const i1 = row * width + col + 1;
      const i2 = row * width + col + 2;
      const i3 = (row + 1) * width + col + 1;
      const i4 = (row + 1) * width + col + 2;
      // Winding reversed vs. the naive order: py is mirrored (north = +Y),
      // which flips handedness — this keeps terrain faces pointing up (+Z).
      obj += `f ${i1}/${i1}/${i1} ${i3}/${i3}/${i3} ${i2}/${i2}/${i2}\n`;
      obj += `f ${i2}/${i2}/${i2} ${i3}/${i3}/${i3} ${i4}/${i4}/${i4}\n`;
    }
  }

  return obj;
};

/**
 * Generate OBJ for extruded buildings.
 * Uses the same coordinate system as terrain (Z-up, meters).
 *
 * buildingGeometry produces positions centered on (0,0) (matching the
 * centered PlaneGeometry used by the 3D preview). The OBJ export shifts
 * them to the same min-corner frame as exportTerrainOBJ so terrain and
 * buildings line up 1:1 in 3ds Max / Rhino.
 *
 * @param {Object} buildingMeshData - from buildingGeometry
 * @param {number} buildingMeshData.positions - Float32Array xyz
 * @param {number} buildingMeshData.indices - Uint32Array triangles
 * @param {number} buildingMeshData.normals - Float32Array
 * @param {number} realWidth - terrain width in meters (for min-corner shift)
 * @param {number} realHeight - terrain height in meters (for min-corner shift)
 * @returns {string} OBJ file content
 */
export const exportBuildingsOBJ = (buildingMeshData, realWidth, realHeight) => {
  const { positions, indices, normals } = buildingMeshData;
  const vertCount = positions.length / 3;
  const offsetX = realWidth / 2;
  const offsetY = realHeight / 2;

  let obj = '# OSM Buildings generated by Negativ Tools\n';
  obj += '# Coordinate system: Z-up (Rhino/3ds Max compatible)\n\n';
  obj += 'o buildings\n';

  for (let i = 0; i < vertCount; i++) {
    obj += `v ${(positions[i*3] + offsetX).toFixed(3)} ${(positions[i*3+1] + offsetY).toFixed(3)} ${positions[i*3+2].toFixed(3)}\n`;
  }

  obj += '\n';
  for (let i = 0; i < vertCount; i++) {
    obj += `vn ${normals[i*3].toFixed(4)} ${normals[i*3+1].toFixed(4)} ${normals[i*3+2].toFixed(4)}\n`;
  }

  obj += '\n';
  for (let i = 0; i < indices.length; i += 3) {
    const a = indices[i] + 1;
    const b = indices[i+1] + 1;
    const c = indices[i+2] + 1;
    obj += `f ${a}//${a} ${b}//${b} ${c}//${c}\n`;
  }

  return obj;
};

/**
 * Download a string as a file.
 */
export const downloadBlob = (content, filename, mimeType = 'text/plain') => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.download = filename;
  link.href = url;
  link.click();
  URL.revokeObjectURL(url);
};

/**
 * Download a data URL as a file.
 */
export const downloadDataUrl = (dataUrl, filename) => {
  const link = document.createElement('a');
  link.download = filename;
  link.href = dataUrl;
  link.click();
};
